// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.edu.ufpb.nhrf.musicstreamer.repository;

import br.edu.ufpb.nhrf.musicstreamer.repository.ArtistRepository;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ArtistRepository_Roo_Jpa_Repository {
    
    declare @type: ArtistRepository: @Transactional(readOnly = true);
    
}
